title = "Repli"  # From Git
gitRepoUrl = "https://github.com/arxkdev/Repli" # From Git

gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = true # Optional

[[home.features]]
title = "Simple"
description = "Repli is a simple, easy to use, and lightweight replication library for Roblox."

[[home.features]]
title = "Quick"
description = "Repli is a quick and easy way to replicate data between the client and server."

[[home.features]]
title = "Lightweight"
description = "Repli is a lightweight library that doesn't take up much space."

[[classOrder]]
section = "Repli"
classes = ["RepliClient", "RepliServer"]

[[classOrder]]
section = "Util"
classes = ["Promise", "Signal", "Error"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Kumarion"
projectName = "Repli"
url = "https://arxk.io"
baseUrl = "/Repli/"
tagline = "Simple. Quick. Lightweight replication library for Roblox."

[footer]
style = "dark"
copyright = "Copyright © 2023 Kumarion. Built with Moonwave and Docusaurus"